# Generated by Django 2.0.8 on 2018-11-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created', '-modified']},
        ),
    ]
