# Generated by Django 2.0.8 on 2018-11-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20180818_0718'),
        ('articles', '0002_auto_20181103_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='patients.Patient'),
        ),
    ]
