# Generated by Django 2.0.8 on 2018-11-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
