# Generated by Django 2.0.8 on 2018-11-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181103_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='articles', to='articles.Tag'),
        ),
    ]
