# Generated by Django 2.0.8 on 2018-11-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20181113_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
