site_name: BackendRESTApi
site_description: BackendRESTApi for mediscri
repo_url: https://github.com/mhoonjeon/mediscri
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/mhoonjeon">mhoonjeon</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Charts: 'api/charts.md'
    - Progress_charts: 'api/progress_charts.md'
    - Patients: 'api/patients.md'
    - Articles(=Questions): 'api/articles.md'
    - Comments: 'api/comments.md'
    - Tags: 'api/tags.md'
