# Generated by Django 2.0.8 on 2018-10-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20181031_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresschart',
            name='admission_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_charts', to='charts.AdmissionChart'),
        ),
    ]
