# Generated by Django 2.0.8 on 2018-11-13 02:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20181031_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionchart',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='dx',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='fhx',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='labs',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='pe',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='pi',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='pmhx',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='psxhx',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='ros',
        ),
        migrations.RemoveField(
            model_name='admissionchart',
            name='shx',
        ),
        migrations.AddField(
            model_name='admissionchart',
            name='note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
