# Generated by Django 2.0.8 on 2018-11-13 02:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_auto_20181113_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresschart',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='progresschart',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='progresschart',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='progresschart',
            name='subjective',
        ),
        migrations.AddField(
            model_name='progresschart',
            name='note',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
