# Generated by Django 2.0.7 on 2018-10-31 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20180818_0718'),
        ('charts', '0002_auto_20180823_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionChart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cc', models.TextField(blank=True, null=True)),
                ('pi', models.TextField(blank=True, null=True)),
                ('pmhx', models.TextField(blank=True, null=True)),
                ('psxhx', models.TextField(blank=True, null=True)),
                ('fhx', models.TextField(blank=True, null=True)),
                ('shx', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('ros', models.TextField(blank=True, null=True)),
                ('pe', models.TextField(blank=True, null=True)),
                ('labs', models.TextField(blank=True, null=True)),
                ('dx', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_charts', to='patients.Patient')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressChart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('admission_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_charts', to='charts.AdmissionChart')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='chart',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
