# Generated by Django 2.0.7 on 2018-08-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['-id']},
        ),
    ]
