# Generated by Django 2.0.7 on 2018-10-29 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_auto_20180820_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='deep_output',
        ),
    ]
