# Generated by Django 2.0.7 on 2018-08-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[(0, 'male'), (1, 'female')], default=0),
        ),
    ]
